/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import static utp.misiontic2022.c2.p47.reto4.vista.VistaRequerimientos.requerimiento01;
import static utp.misiontic2022.c2.p47.reto4.vista.VistaRequerimientos.requerimiento02;
import static utp.misiontic2022.c2.p47.reto4.vista.VistaRequerimientos.requerimiento03;

//import static utp.misiontic2022.c2.p47.reto4.vista.VistaRequerimientos.controlador;

/**
 *
 * @author Belphegor
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    //JTable tabla1, tabla2, tabla3 =new JTable();
    //JScrollPane Panel=new JScrollPane();
    
    
    public Formulario() throws SQLException{
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rq01 = new javax.swing.JButton();
        Rq02 = new javax.swing.JButton();
        Rq03 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jResultado = new javax.swing.JTable();
        jEtiqueta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        Rq01.setText("Requerimientos 1");
        Rq01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rq01ActionPerformed(evt);
            }
        });

        Rq02.setText("Requerimientos 2");
        Rq02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rq02ActionPerformed(evt);
            }
        });

        Rq03.setText("Requerimientos 3");
        Rq03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rq03ActionPerformed(evt);
            }
        });

        jResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jResultado);

        jEtiqueta.setText("No ha realizado Consulta");

        jLabel1.setText("Reto 05");

        jLabel2.setText("Jhon Jairo Cardona Osorno");

        jLabel3.setText("Grupo 20");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rq01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(Rq02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(Rq03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jEtiqueta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rq01)
                    .addComponent(Rq02)
                    .addComponent(Rq03))
                .addGap(18, 18, 18)
                .addComponent(jEtiqueta)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    


    
    private void Rq01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rq01ActionPerformed
        try {
            // TODO add your handling code here:
            jResultado.setModel(new javax.swing.table.DefaultTableModel(
                    requerimiento01(),
                    new String [] {
                        "Nombre", "Primer Apellido", "Segundo Apellido", "Salario"
                    }
            ));
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jEtiqueta.setText("Conocer el nombre, apellidos y salarios de los lideres cuyo segundo apellido sea ‘Ortiz’");
    }//GEN-LAST:event_Rq01ActionPerformed

    private void Rq02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rq02ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            jResultado.setModel(new javax.swing.table.DefaultTableModel(
                    requerimiento02(),
                    new String [] {
                        "Nombre"
                    }
            ));
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jEtiqueta.setText("nombre del Lider ->la primera letra sea en minúscula y las demás en mayúscula.");
    }//GEN-LAST:event_Rq02ActionPerformed

    private void Rq03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rq03ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            jResultado.setModel(new javax.swing.table.DefaultTableModel(
                    requerimiento03(),
                    new String [] {
                        "Residencia", "Salario"
                    }
            ));
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jEtiqueta.setText("Saber la suma de los salarios de todos los lideres por su ciudad de residencia");
    }//GEN-LAST:event_Rq03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Formulario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rq01;
    private javax.swing.JButton Rq02;
    private javax.swing.JButton Rq03;
    private javax.swing.JLabel jEtiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jResultado;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
